# Generated by Django 2.2.6 on 2019-11-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rkigeonameapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternatename',
            options={'ordering': ['alternatenameid'], 'verbose_name': 'Alternativname', 'verbose_name_plural': 'Alternativnamen'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Kontinent', 'verbose_name_plural': 'Kontinente'},
        ),
        migrations.AlterModelOptions(
            name='countryinfo',
            options={'ordering': ['name'], 'verbose_name': 'Land', 'verbose_name_plural': 'Länder'},
        ),
        migrations.AlterModelOptions(
            name='featurecode',
            options={'ordering': ['-searchorder_detail', 'code'], 'verbose_name': 'Featurecode', 'verbose_name_plural': 'Featurecodes'},
        ),
        migrations.AlterModelOptions(
            name='geoname',
            options={'ordering': ['-population', 'name'], 'verbose_name': 'Geoname', 'verbose_name_plural': 'Geonames'},
        ),
        migrations.AlterModelOptions(
            name='hierarchy',
            options={'ordering': ['parent__geonameid'], 'verbose_name': 'Hierarchie', 'verbose_name_plural': 'Hierarchien'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-geonameid__population', 'name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regionen'},
        ),
        migrations.AlterField(
            model_name='featurecode',
            name='code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Featurecode'),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='is_custom_entry',
            field=models.BooleanField(blank=True, default=True, editable=False, null=True, verbose_name='Is custom entry?'),
        ),
        migrations.AlterField(
            model_name='region',
            name='fcode',
            field=models.ForeignKey(blank=True, db_column='fcode', null=True, on_delete=django.db.models.deletion.CASCADE, to='rkigeonameapi.Featurecode', verbose_name='Featurecode'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geonameid',
            field=models.ForeignKey(blank=True, db_column='geonameid', null=True, on_delete=django.db.models.deletion.CASCADE, to='rkigeonameapi.Geoname', verbose_name='Geoname-Objekt'),
        ),
        migrations.AlterField(
            model_name='region',
            name='laender',
            field=models.ManyToManyField(to='rkigeonameapi.Countryinfo', verbose_name='Beinhaltete Länder'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Region-ID'),
        ),
    ]
